"""
schemas.py
Pydantic models for all API request and response shapes.
The response schema is non-negotiable per the assignment spec.
"""

from pydantic import BaseModel, Field
from typing import Literal


class Message(BaseModel):
    role: Literal["user", "assistant"]
    content: str


class ChatRequest(BaseModel):
    messages: list[Message] = Field(
        ...,
        min_length=1,
        description="Full conversation history. Must contain at least one message."
    )


class Recommendation(BaseModel):
    name: str = Field(..., description="Assessment name from SHL catalog")
    url: str = Field(..., description="Verified catalog URL — never generated by LLM")
    test_type: str = Field(
        ...,
        description="All applicable SHL type codes for this assessment, comma-separated "
        "(e.g. A, K, S) in stable catalog order — not only the primary category. "
        "S = Simulations.",
    )


class ChatResponse(BaseModel):
    reply: str = Field(..., description="Agent's natural language response")
    recommendations: list[Recommendation] = Field(
        default_factory=list,
        description="Empty while clarifying. 1–10 items when committed to shortlist."
    )
    end_of_conversation: bool = Field(
        default=False,
        description="True only when agent considers the task complete."
    )


class HealthResponse(BaseModel):
    status: str = "ok"
